name: Deploy printer-app

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}


      - name: Deploy to Azure VM
        run: |
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ azureuser@${{ vars.VM_HOST }}:/var/www/printer/

      - name: Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ vars.VM_HOST }} "sudo systemctl reload nginx"
