name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install deps & build
      run: |
        npm ci
        npm run build

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy via rsync
      run: |
        rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ azureuser@${{ vars.VM_HOST }}:/var/www/printer/


    - name: Reload nginx
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@${{ vars.VM_HOST }} "sudo systemctl reload nginx"

        # trigger reload
